server:
  port: 8088


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.187.22.37:3310/doori?serverTimezone=Asia/Seoul
    username: dbuser
    password: password!
  jpa:
    hibernate:
      ddl-auto: none #create update none

    show-sql: true
  main:
    allow-circular-references: true
jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #key size (512bit)
  # https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000	# 1 day
  refresh-expiration: 604800000 #7days
